
services:
  backend:
    build: ./src/backend
    container_name: stp_api
    ports:
      - "8000:8000"
    volumes:
      - ./src/backend:/app
    depends_on: 
      - postgres
    env_file:
      .env

  frontend:
    build: ./src/frontend
    container_name: stp_app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./src/frontend:/app
    environment:
      - STREAMLIT_SERVER_RUN_ON_SAVE=true

  postgres:
    image: postgres:latest
    container_name: stp_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes: 
  postgres_data: